config/routes.rb
Webpage::Application.routes.draw do
  root 'sites#index'
  get  'search'    => 'sites#index' , as: :search
  post 'search'    => 'sites#search', as: :search_form
  get  'sites/:id' => 'sites#show'  , as: :sites_view

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :site
end

app/models/ratings.rb
class Ratings < ActiveRecord::Base
	  belongs_to :site

end

app/models/review.rb
class Review < ActiveRecord::Base
end

app/models/site.rb
class Site < ActiveRecord::Base
	has_many :comments
	has_many :ratings
	validates :lat, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render :action: 'show', status: :created, location: @review }
      else
        format.html { render action: 'new' }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:name, :description, :picture)
    end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  require 'httparty'
  require 'json'
  require 'PPApi'
  require 'wikipedia'

  def index
    @search_results = []
  end

  def search
    @search_results = []
    if params[:codigo].present?
      response = HTTParty.get("http://maps.googleapis.com/maps/api/geocode/json?address=#{CGI.escape(params[:codigo])}&sensor=false")
      results = response["results"].first
      geometry = results["geometry"]
      location = geometry["location"]
      lat = location["lat"].to_i
      lng = location["lng"].to_i
      @search_results=PPApi.search_result(lat,lng)
      puts @search_result.inspect
      render 'index'
    end
  end

  def show
    id = params[:id]
    @site = PPApi.get_site(id)
    @page = Wikipedia.find(@site["official"]["NAME"])
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/comments/index.html.erb
<div> <p> Hello Comments! </p></div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav navbar-nav">
  <li>
    <%= link_to "Search", search_path %>
  </li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Protected Areas" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails Bootstrap" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?sensor=false" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      <nav class="navbar navbar-default" role="navigation">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        <%= link_to "WCMC API-C", root_path, class: "navbar-brand" %>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
      <div class="row">
        <div class="col-md-12">
          <%= render 'layouts/messages' %>
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/reviews/_form.html.erb
<%= form_for(@review) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.text_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing review</h1>

<%= render 'form' %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<h1>Listing reviews</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Picture</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.name %></td>
        <td><%= review.description %></td>
        <td><%= review.picture %></td>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<h1>New review</h1>

<%= render 'form' %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @review.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @review.description %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @review.picture %>
</p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>

app/views/sites/index.html.erb
<div class="row search-form">
  <div class="col-md-10 col-md-offset-1">
    <div class="row">
      <div class="col-md-10 col-md-offset-2">
        <h3>Discover the most amazing protected areas!</h3>
      </div>
    </div>
    <%= form_tag(search_form_path, class: "form-inline", role: "form") do %>
      <div class="col-md-10 form-group">
        <input type="text" class="form-control" name="codigo" placeholder="Type a place to search" required>
      </div>
      <button type="submit" class="btn btn-primary">Search</button>
    <% end %>
  </div>
</div>
<div class="row">
  <% if @search_results.any? %>
    <div class="col-md-4 search-results">
      <h3>Protected Areas:</h3>
      <ul class="list-group">
        <% @search_results.each do |result| %>
          <li class="list-group-item">
            <span class="glyphicon glyphicon-home"></span>
            <%= link_to result["official"]["NAME"], sites_view_path(id: result["official"]["WDPAID"]) %> <br> 
            <%= link_to '0 Comments', sites_view_path(id: result["official"]["WDPAID"], anchor: "disqus_thread") %> </li>
</li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <% if @search_results.any? %>
    <div class="col-md-8">
  <% else %>
    <div class="col-md-12">
  <% end %>
        <div id="map-canvas"></div>
    </div>
</div>


<script type="text/javascript">
  setTimeout(function(){
    var bounds = new google.maps.LatLngBounds();
    var markersArray = [];
    <% @search_results.each do |result| %>
      <% geom = result["official"]["GEOM"].split(",").first
          lat = geom.match(/\(\(\((.*) (.*)/)[2]
          lon = geom.match(/\(\(\((.*) (.*)/)[1]
      %>

      var marker = new google.maps.Marker({
        position: new google.maps.LatLng(<%= lat %>,<%= lon %>),
        map: map,
        title: '<%= result["official"]["NAME"] %>'
      });

      markersArray.push(marker);
    <% end %>

    for (var i=0; i < markersArray.length; i++) {
        bounds.extend(markersArray[i].getPosition());
    }
    map.fitBounds(bounds);

  }, 1000);

</script>

    <script type="text/javascript">
    /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
    var disqus_shortname = 'protectedareasintern'; // required: replace example with your forum shortname

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function () {
        var s = document.createElement('script'); s.async = true;
        s.type = 'text/javascript';
        s.src = '//' + disqus_shortname + '.disqus.com/count.js';
        (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
    }());
    </script>

app/views/sites/show.html.erb
<div class="row">
	<div class="col-md-11 col-md-offset-1" >
		<h2><%= @site["official"]["NAME"] %></h2>
	</div>
</div>

<div class="row">
	<div class="col-md-7 col-md-offset-1" >
		<script type="text/javascript" src="http://www.panoramio.com/wapi/wapi.js?v=1"></script>
		<div id="photowall"></div>
		<script type="text/javascript">
		var birds = {'tag': '<%= @name%>'};
		var list_options = {'width': 600, 'height': 400};
		var widget = new panoramio.PhotoWidget('photowall', birds, list_options);
		widget.setPosition(0);
		</script>
	</div>
	<div class="col-md-4">
		<table class="table table-striped table-bordered">
			<tr>
				<td>Original Name:<br><%= @site["official"]["ORIG_NAME"] %></td>
			</tr>
			<tr>
				<td>Country:<br> <%= @site["official"]["COUNTRY"] %></td>
			</tr>
			<tr>
				<td>Status Year: <br> <%= @site["official"]["STATUS_YR"] %></td>
			</tr>
			<tr>
				<td>English Designation: <br> <%= @site["official"]["DESIG_ENG"] %></td>
			</tr>

		</table>
	</div>
</div>
<br/>
<br/>

<div class="row">
	
	<div class="col-md-7 col-md-offset-1" >
		<div id="disqus_thread"></div>
		<script type="text/javascript">
		/* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'protectedareasintern'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
        	var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        	dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        	(document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
        </script>
        <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
        <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
    </div>

    <!--<div class="col-md-4" >
	<%if @page %>
		<h1><%= @page.title %></h1>
		<% if @page.image_urls.any? %>
			<% @page.image_urls.each do |img_url| %>
				<%= link_to image_tag(img_url, width: 100), img_url %>
			<% end %>
		<% end %>
		<p><%= @page.content %></p>
		
	<% end %>
	</div>-->
</div>